### ISSUE TITLE
time zone issue in announcement emails

### ISSUE THREAD

**Issue by vpnagraj** [uvasomrc/ed-platform#12]
i know there was an issue with the time zone for registration confirmation emails *not* being EST ... i believe something similar is going with the instructor announcement emails ... see below (should have said march 15 3:00PM)

<img width="599" alt="screen shot 2018-01-26 at 3 45 01 pm" src="https://user-images.githubusercontent.com/8546787/35459865-e7b39b64-02af-11e8-9eb9-6c5a89ab1e8d.png">

**Comment by danfunk** [comment]
I've gone through all the email mesages and changed any date time references to reformat to Eastern Standard time.  This code was pushed on Sunday Jan 28th.
