### ISSUE TITLE
preserve formatting in announcement emails

### ISSUE THREAD

**Issue by vpnagraj** [uvasomrc/ed-platform#13]
i just got an email announcement for a workshop cory is teaching ... looks like he used formatting (hard returns) when drafting the email in the platform, but when delivered it was stripped of that formatting:

<img width="651" alt="screen shot 2018-01-29 at 1 55 15 pm" src="https://user-images.githubusercontent.com/8546787/35528638-7c5aeeea-04fc-11e8-9e5f-02e1671db37a.png">

**Comment by danfunk** [comment]
Email messages from instructors - to both session attendees and followers - now support Markdown.
