### ISSUE TITLE
Instructors should be able to view past sessions

### ISSUE THREAD

**Issue by crd2jg** [uvasomrc/ed-platform#15]
Now that my session for Introduction to Matlab is complete, I can no longer see the list of people who attended or the emails that I sent them.  I noticed that it stuck around for a few hours after the completion of the session.

It should keep the past session history viewable by the instructor including persons who registered/attended, emails sent, and the ability to email for a limited time (a few days after the conclusion).

**Comment by danfunk** [comment]
Hi Cory,  Thank you for the thoughtful feedback.  You are absolutely right.  I think you should always be able to see past sessions and in the heat of getting everything up and running I must have done something to prevent this.  I'll try and get this working by tomorrow afternoon in case you want to follow up with the class.

**Comment by danfunk** [comment]
Cory, I've pushed up a chance that will allow instructors to see all the past sessions for any workshops they instruct.  I hope this update is timely enough that you can get whatever you wanted out to your students.
