### ISSUE TITLE
Width issue on track pages

### ISSUE THREAD

**Issue by nmagee** [uvasomrc/ed-platform#2]
When viewing a track like the one below, there's a slight width difference between the site header and the track header -- the latter is slightly narrower, by 10-20px or so.

https://education.cadre.virginia.edu/#/track/274

I'm seeing this in chrome, but the headers are nice and flush in Safari.

**Comment by nmagee** [comment]
I just forced a refresh on the page in Chrome, and it's all even now, so I think it's good.

Does anyone else see this at all?

**Comment by parikhhi** [comment]
@nmagee - I am experiencing similar behavior with Chrome. The track image is narrower than the header, but a refresh on the page aligns them.

**Comment by danfunk** [comment]
Committed and deployed a fix that will correct this issue, and several others related to the header layout and formatting on mobile an desktop.
