### ISSUE TITLE
User info edits not persisting after signing back in

### ISSUE THREAD

**Issue by orksomrc** [uvasomrc/ed-platform#3]
Once a user updates their information on the "Edit Account" page (inc. Name, About, Picture) all changes are saved. However upon signing out, and then signing back in, the new user profile changes don't show up and are reverted back to the pre-edit state. Confirmed with cache-off and on multiple browsers.

**Comment by danfunk** [comment]
I just pushed a fix and tested.  This is fixed and working correctly.

**Comment by vpnagraj** [comment]
@danfunk can you please take another look at this? one of the instructors ("John") tried to edit his profile again (after this push) to add his last name and a profile picture and the changes still weren't saved

**Comment by danfunk** [comment]
I believe this is fixed now.  Was able to log in as John and change his details without issue.
